default: &default
  adapter: sqlite3
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: 127.0.0.1 

development:
  primary:
    <<: *default
    database: db_sample_development
    port: 33061
  primary_replica:
    <<: *default
    database: db_sample_development
    port: 33062
    replica: true

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
